// <auto-generated />
using System;
using GoodHouse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoodHouse.Migrations
{
    [DbContext(typeof(GoodHouseDbContext))]
    [Migration("20210411161125_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoodHouse.Models.Entity.HouseObject", b =>
                {
                    b.Property<Guid>("HouseObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DealDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditeUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<decimal>("HouseAge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsParkingSpace")
                        .HasColumnType("bit");

                    b.Property<decimal>("ParkingSpacePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ParkingSpaceSqureFeet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SquareFeet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SquareFeetUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalFloor")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HouseObjectId");

                    b.ToTable("HouseObjects");
                });

            modelBuilder.Entity("GoodHouse.Models.Entity.HousingLayout", b =>
                {
                    b.Property<Guid>("HousingLayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Bathroom")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditeUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HouseObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LivingRoom")
                        .HasColumnType("int");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.HasKey("HousingLayoutId");

                    b.HasIndex("HouseObjectId");

                    b.ToTable("HousingLayouts");
                });

            modelBuilder.Entity("GoodHouse.Models.Entity.HousingLayout", b =>
                {
                    b.HasOne("GoodHouse.Models.Entity.HouseObject", "HouseObject")
                        .WithMany("HousingLayouts")
                        .HasForeignKey("HouseObjectId");

                    b.Navigation("HouseObject");
                });

            modelBuilder.Entity("GoodHouse.Models.Entity.HouseObject", b =>
                {
                    b.Navigation("HousingLayouts");
                });
#pragma warning restore 612, 618
        }
    }
}
